version: '3.9'

services:
 backend:
  build:
   context: ./backend
  ports:
   - "5001:5000"
  volumes:
   - ./backend:/app
  restart: always

 frontend:
  build:
   context: ./frontend
  ports:
    - "8080:80"
  volumes:
    - ./frontend:/app  ##volume bindmount
  restart: always
